"""add prerequisites, assets, chunks, enrollments, progress, failed events

Revision ID: 704fb4a4e3fc
Revises: ab988ed920ef
Create Date: 2026-09-22 13:57:09.356242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '704fb4a4e3fc'
down_revision: Union[str, Sequence[str], None] = 'ab988ed920ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_events',
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("source IN ('kafka', 'celery', 'temporal')", name='ck_failed_events_source_valid'),
    sa.CheckConstraint("status IN ('pending', 'retrying', 'resolved', 'abandoned')", name='ck_failed_events_status_valid'),
    sa.CheckConstraint('retry_count >= 0', name='ck_failed_events_retry_count_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_events_source'), 'failed_events', ['source'], unique=False)
    op.create_index(op.f('ix_failed_events_source_name'), 'failed_events', ['source_name'], unique=False)
    op.create_index(op.f('ix_failed_events_status'), 'failed_events', ['status'], unique=False)
    op.create_table('course_prerequisites',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('prerequisite_course_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('course_id <> prerequisite_course_id', name='ck_course_prerequisites_not_self'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_course_id')
    )
    op.create_index(op.f('ix_course_prerequisites_prerequisite_course_id'), 'course_prerequisites', ['prerequisite_course_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'completed') = (completed_at IS NOT NULL)", name='ck_enrollments_completed_at_matches_status'),
    sa.CheckConstraint("status IN ('active', 'completed', 'withdrawn')", name='ck_enrollments_status_valid'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_index('uq_enrollments_one_active', 'enrollments', ['student_id', 'course_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('assets',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('extraction_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("extraction_status IN ('pending', 'extracting', 'done', 'failed', 'not_applicable')", name='ck_assets_extraction_status_valid'),
    sa.CheckConstraint('size_bytes >= 0', name='ck_assets_size_non_negative'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_extraction_status'), 'assets', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_assets_lesson_id'), 'assets', ['lesson_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'lesson_id', name='uq_lesson_progress_once')
    )
    op.create_index(op.f('ix_lesson_progress_enrollment_id'), 'lesson_progress', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_lesson_id'), 'lesson_progress', ['lesson_id'], unique=False)
    op.create_table('chunks',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_chunks_position_non_negative'),
    sa.CheckConstraint('token_count > 0', name='ck_chunks_token_count_positive'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'asset_id', 'position', name='uq_chunks_source_position', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_chunks_asset_id'), 'chunks', ['asset_id'], unique=False)
    op.create_index(op.f('ix_chunks_content_hash'), 'chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_chunks_lesson_id'), 'chunks', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_lesson_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_content_hash'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_asset_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_lesson_progress_lesson_id'), table_name='lesson_progress')
    op.drop_index(op.f('ix_lesson_progress_enrollment_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_assets_lesson_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_extraction_status'), table_name='assets')
    op.drop_table('assets')
    op.drop_index('uq_enrollments_one_active', table_name='enrollments', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_course_prerequisites_prerequisite_course_id'), table_name='course_prerequisites')
    op.drop_table('course_prerequisites')
    op.drop_index(op.f('ix_failed_events_status'), table_name='failed_events')
    op.drop_index(op.f('ix_failed_events_source_name'), table_name='failed_events')
    op.drop_index(op.f('ix_failed_events_source'), table_name='failed_events')
    op.drop_table('failed_events')
    # ### end Alembic commands ###
