"""The declarative base, and the bits of it every table shares.

Kept separate from session.py on purpose. Models only need Base, and importing
it should not drag in engine and connection setup - that separation is also
what stops the circular imports that otherwise appear here.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Parent of every model.

    Inheriting from it does two things. It gives the class the machinery to
    become a table, and it registers the table on `Base.metadata` - the list
    Alembic reads to work out what your schema should look like.

    A model that never gets imported is therefore invisible to Alembic, and
    silently missing from your migrations. That is why models.py imports every
    model module.
    """


class UUIDMixin:
    """A uuid primary key, generated by the application.

    A "mixin" is a small class holding a few fields, that models inherit
    alongside Base to pick those fields up. It saves writing the same three
    columns on ten tables.

    UUID rather than an auto-incrementing integer because Module 3's outbox
    pattern needs the id to exist *before* the row is written. The database
    assigns a sequential integer on insert, which is too late.

    `default=uuid.uuid4` passes the function itself, not a call to it. Note the
    missing brackets: SQLAlchemy calls it once per row. With brackets it would
    run once at import and every row would get the same id.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )


class TimestampMixin:
    """created_at and updated_at, maintained by the database.

    `server_default=func.now()` means Postgres fills these in, not Python. That
    matters: every row gets a consistent time from one clock, and rows created
    by a migration or a hand-written SQL fix are stamped too.

    timestamptz, never plain timestamp - see docs/SCHEMA.md. Plain timestamp
    drops the timezone silently and gives wrong answers the moment anything
    crosses one, including the "average time to complete a course" metric.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
